# Autogenerated module
from typing import Dict, List
import os
from openai import OpenAI # pyright: ignore[reportMissingImports]
from dotenv import load_dotenv # pyright: ignore[reportMissingImports] # Add this import

load_dotenv() # Add this line before the key check

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise RuntimeError("OPENROUTER_API_KEY is not set")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)

# -------------------------
# Required Input Contract
# -------------------------
REQUIRED_FIELDS = [
    "persona_label",
    "risk_level",
    "effort_outcome_gap",
    "primary_lever",
    "key_drivers",
    "student_context",
]


def validate_input_contract(payload: Dict) -> None:
    """
    Ensures the GenAI engine only runs on complete, trusted analytics.
    Raises ValueError if anything critical is missing.
    """

    missing = [field for field in REQUIRED_FIELDS if field not in payload]
    if missing:
        raise ValueError(f"Missing required GenAI inputs: {missing}")

    context = payload["student_context"]

    for field in ["School_Type_Public", "learning_disabilities"]:
        if field not in context:
            raise ValueError(f"Missing student_context field: {field}")


# -------------------------
# Prompt Builder
# -------------------------
def build_prompt(payload: Dict) -> List[Dict]:
    """
    Builds the SYSTEM + USER messages.
    MASTER PROMPT TEXT is fixed and deterministic.
    """

    system_message = """
You are an educational decision-support assistant.
Your role is to help teachers understand learning challenges and choose practical, ethical interventions.
You must not label students negatively or make medical or psychological diagnoses.
Focus on observable behaviors, learning conditions, and realistic actions.
Use clear, respectful, non-judgmental language.
""".strip()

    user_message = f"""
You are given structured analytical outputs from a learning analytics system.

Your task is to generate THREE outputs for a teacher:

1. A brief explanation of why the student may be underperforming.
2. A targeted intervention playbook with clear ownership and success metrics.
3. A short, constructive communication draft to parents.

IMPORTANT RULES:
- Base your reasoning ONLY on the provided data.
- Do NOT speculate or diagnose.
- Keep language practical and respectful.
- Avoid generic advice like “study more” or “try harder”.

STUDENT ANALYTICS:
Persona: {payload['persona_label']}
Risk Level: {payload['risk_level']}
Effort–Outcome Gap: {payload['effort_outcome_gap']}
Primary Intervention Lever: {payload['primary_lever']}
Key Drivers: {payload['key_drivers']}

STUDENT CONTEXT:
School Type: {payload['student_context']['School_Type_Public']}
Learning Disabilities: {payload['student_context']['learning_disabilities']}

OUTPUT FORMAT (STRICT):

### WHY THIS STUDENT IS STRUGGLING (2 sentences max)

### TARGETED INTERVENTION PLAYBOOK
- Owner:
  Action:
  Success Metric:
  Timeframe:

(Provide 2–3 actions maximum)

### PARENT COMMUNICATION DRAFT
""".strip()

    return [
        {"role": "system", "content": system_message},
        {"role": "user", "content": user_message},
    ]


# -------------------------
# Main GenAI Entry Point
# -------------------------
def generate_teacher_explanation(
    payload: Dict,
    model: str = "z-ai/glm-4.5-air:free",
    temperature: float = 0.2,
) -> str:
    """
    Main entry point for Feature 7.
    Returns formatted text ready for teacher UI.
    """

    validate_input_contract(payload)
    messages = build_prompt(payload)

    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
    )

    return response.choices[0].message.content