import os

# Define the folder and file structure
structure = {
    "ps_2/notebooks": ["01_full_analysis.ipynb"],
    "ps_2/src/data": ["preprocessing.py"],
    "ps_2/src/models": ["exam_score_model.py"],
    "ps_2/src/features": [
        "effort_gap.py", 
        "resource_mismatch.py", 
        "persona_clustering.py", 
        "primary_lever.py", 
        "intervention_simulation.py"
    ],
    "ps_2/src/explainability": ["genai_engine.py"],
    "ps_2/src/config": [],
    "ps_2/ui": ["teacher_dashboard.py"],
    "ps_2": ["README.md"]
}

def create_structure():
    for folder, files in structure.items():
        # Create the directory
        os.makedirs(folder, exist_ok=True)
        # Create each file in that directory
        for file in files:
            file_path = os.path.join(folder, file)
            if not os.path.exists(file_path):
                with open(file_path, 'w') as f:
                    if file.endswith('.py'):
                        f.write("# Autogenerated module")
                    elif file.endswith('.md'):
                        f.write("# Project PS_2\nLearning Analytics System")
                print(f"Created: {file_path}")

if __name__ == "__main__":
    create_structure()
    print("\n✅ Hackathon project structure is ready!")