# Autogenerated module
import pandas as pd


def compute_effort_outcome_gap(
    df: pd.DataFrame,
    model,
    scaler,
    feature_cols,
):
    X = df[feature_cols]
    X_scaled = scaler.transform(X) # Ensure X is a DataFrame here

    predicted = model.predict(X_scaled)

    df = df.copy()
    df["predicted_exam_score"] = predicted
    df["effort_outcome_gap"] = df["Exam_Score"] - predicted

    mean_gap = df["effort_outcome_gap"].mean()
    std_gap = df["effort_outcome_gap"].std()

    df["effort_outcome_gap_z"] = (
        (df["effort_outcome_gap"] - mean_gap) /(std_gap + 1e-9)
    )

    return df
