# Autogenerated module
def simulate_intervention_effect(
    row,
    model,
    scaler,
    feature_columns,
):
    lever = row["primary_lever"]

    if lever == "NO_INTERVENTION":
        return 0.0

    current_features = row[feature_columns].copy()
    future_features = current_features.copy()

    if lever == "SLEEP":
        future_features["Sleep_Hours"] += 1

    elif lever == "ATTENDANCE":
        future_features["Attendance"] = min(
            future_features["Attendance"] + 10, 100
        )

    elif lever == "MOTIVATION":
        future_features["Motivation_Level"] = min(
            future_features["Motivation_Level"] + 1, 2
        )

    elif lever == "RESOURCES":
        future_features["Access_to_Resources"] = min(
            future_features["Access_to_Resources"] + 1, 2
        )

    elif lever == "TUTORING":
        future_features["Tutoring_Sessions"] += 1

    current_scaled = scaler.transform(
        current_features.values.reshape(1, -1)
    )
    future_scaled = scaler.transform(
        future_features.values.reshape(1, -1)
    )

    current_pred = model.predict(current_scaled)[0]
    future_pred = model.predict(future_scaled)[0]

    return future_pred - current_pred


def add_expected_score_improvement(
    df,
    model,
    scaler,
    feature_columns,
):
    df = df.copy()
    df["expected_score_improvement"] = df.apply(
        simulate_intervention_effect,
        axis=1,
        model=model,
        scaler=scaler,
        feature_columns=feature_columns,
    )
    return df