# Autogenerated module
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans


def prepare_clustering_features(
    df: pd.DataFrame,
    feature_cols,
):
    df = df.copy()
    df["gap_for_clustering"] = df["effort_outcome_gap_z"].clip(-3, 3)

    X = df[feature_cols]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    return X_scaled, scaler

def assign_persona_clusters(
    df: pd.DataFrame,
    X_cluster_scaled,
    n_clusters: int = 4,
):
    kmeans = KMeans(
        n_clusters=n_clusters,
        random_state=42,
        n_init=10,
    )

    df = df.copy()
    df["Cluster"] = kmeans.fit_predict(X_cluster_scaled)

    return df, kmeans


def map_failure_mode_persona(df: pd.DataFrame):
    persona_map = {
        0: "Disengaged Despite Resources",
        1: "Resilient Low-Resource Learners",
        2: "Overworked Strugglers",
        3: "Motivated but Inconsistent",
    }

    df = df.copy()
    df["failure_mode_persona"] = df["Cluster"].map(persona_map)

    return df