# Autogenerated module
def assign_primary_lever(row):
    if row["effort_outcome_gap_z"] >= -0.2:
        return "NO_INTERVENTION"

    if row["Sleep_Hours"] <= 6:
        return "SLEEP"

    if row["Attendance"] < 75:
        return "ATTENDANCE"

    if row["Access_to_Resources"] <= 1:
        return "RESOURCES"

    if row["Motivation_Level"] <= 1:
        return "MOTIVATION"

    return "TUTORING"


def add_primary_lever(df):
    df = df.copy()
    df["primary_lever"] = df.apply(assign_primary_lever, axis=1)
    return df