# Autogenerated module
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


def compute_resource_index(
    df: pd.DataFrame,
    resource_cols,
):
    scaler = MinMaxScaler()
    norm_cols = [col + "_norm" for col in resource_cols]

    scaled = scaler.fit_transform(df[resource_cols])

    df = df.copy()
    df[norm_cols] = scaled
    df["resource_index"] = df[norm_cols].mean(axis=1)

    return df, scaler


def classify_resource_mismatch(row):
    r = row["resource_index"]
    g = row["effort_outcome_gap_z"]

    if r >= 0.66 and g <= -1.0:
        return "HIGH"

    if r <= 0.33 and g <= -1.0:
        return "HIGH"

    if g <= -0.5:
        return "MEDIUM"

    return "LOW"


def add_resource_mismatch_flag(df: pd.DataFrame):
    df = df.copy()
    df["resource_mismatch_flag"] = df.apply(
        classify_resource_mismatch,
        axis=1,
    )
    return df