# Autogenerated module
from sklearn.linear_model import LinearRegression
import numpy as np


def train_exam_score_model(X_train_scaled, y_train):
    model = LinearRegression()
    model.fit(X_train_scaled, y_train)
    return model


def predict_exam_score(model, X_scaled):
    return model.predict(X_scaled)


def evaluate_exam_score_model(model, X_test_scaled, y_test):
    y_pred = model.predict(X_test_scaled)
    rmse = np.sqrt(((y_test - y_pred) ** 2).mean())
    r2 = 1 - (
        ((y_test - y_pred) ** 2).sum()
        / ((y_test - y_test.mean()) ** 2).sum()
    )
    return {
        "rmse": rmse,
        "r2": r2,
    }